USE [master]
GO

/****** Object:  Database [CadastroCliente]    Script Date: 26/05/2021 20:47:10 ******/
CREATE DATABASE [CadastroCliente]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CadastroCliente', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CadastroCliente.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CadastroCliente_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CadastroCliente_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CadastroCliente].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CadastroCliente] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CadastroCliente] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CadastroCliente] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CadastroCliente] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CadastroCliente] SET ARITHABORT OFF 
GO

ALTER DATABASE [CadastroCliente] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CadastroCliente] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CadastroCliente] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CadastroCliente] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CadastroCliente] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CadastroCliente] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CadastroCliente] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CadastroCliente] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CadastroCliente] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CadastroCliente] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CadastroCliente] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CadastroCliente] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CadastroCliente] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CadastroCliente] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CadastroCliente] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CadastroCliente] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CadastroCliente] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CadastroCliente] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CadastroCliente] SET  MULTI_USER 
GO

ALTER DATABASE [CadastroCliente] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CadastroCliente] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CadastroCliente] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CadastroCliente] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CadastroCliente] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CadastroCliente] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CadastroCliente] SET  READ_WRITE 
GO

